### ISSUE TITLE
Failing of random generator may slip through

### ISSUE THREAD

**Issue by dirkx** [wyattoday/mod_cspnonce#10]

**Comment by wyattoday** [comment]
We're not going to use the APR RNG (the method we've chosen uses a secure PRNG on every platform).

But thrown returning an error on failure to generate a CSP is a good idea. Please separate it from the rest of your changes and make that 1 or 2 line PR and we'll merge it.

**Comment by wyattoday** [comment]
Thanks, we just committed the change to return 500 on a failure to generate the CSP nonce: https://github.com/wyday/mod_cspnonce/commit/886e28369921207c22511e407e117e783066a7a4

**Comment by dirkx** [comment]
Nice. You could also consider seeding per server (child) init to limit observability.
