### ISSUE TITLE
version 1.4 just returning error 500 in apache 2.4.18

### ISSUE THREAD

**Issue by Kaspanoombro** [wyattoday/mod_cspnonce#11]
Hello,

I just installed the mod_cspnonce 1.14 in Ubuntu server 16.04.07 LTS with apache 2.14.18 and apparently the cspnonce module cannot generate the nonce and makes the apache return error 500. How to solve this?
Thank you.

**Comment by wyattoday** [comment]
Upgrade your kernel.

**Comment by Kaspanoombro** [comment]
i can't.

**Comment by wyattoday** [comment]
Ok. 🤷🏻‍♂️

**Comment by Kaspanoombro** [comment]
I see. Removed your module. Thank you anyway.

**Comment by Kaspanoombro** [comment]
Just to inform you: in your main page you mention that Linux: upgrade to kernel 3.17 or higher. Ubuntu server 16.04.07 LTS has kernel 4.4.0-042stab139.1 but your module does not work.

**Comment by wyattoday** [comment]
16.04 is no longer receiving updates. Update to a supported OS.

Kernel requirements might be higher. I'm not digging into it right now. Just upgrade to a supported OS / kernel and try again.
