### ISSUE TITLE
CSP Nonce gives null value

### ISSUE THREAD

**Issue by sivabalan02** [wyattoday/mod_cspnonce#12]
I am getting null value for the CSP Nonce. Is any particular reason for that?

httpd version -  Apache/2.4.6 (CentOS)
kernal version - 5.4.168-1.el7.elrepo.x86_64
os name and its version   - CentOS Linux 7 (Core)

**Comment by wyattoday** [comment]
No idea. Likely old compiler or old kernel or both.

Use the latest compiler and latest Kernel. No point in adding security to insecure base.
