### ISSUE TITLE
Works for main domain but not for subdomain

### ISSUE THREAD

**Issue by DeepFusion** [wyattoday/mod_cspnonce#14]
Hi, 

The module always works fantastic for our main.domain, but now we deployed an admin panel on admin.main.domain and in html response it loads ...<script src="/js/app.bec01de2.js" nonce="<?= $_SERVER['CSP_NONCE'] ?>"></script>.... instead of f.e. nonce=nonce-3uR3CIhP/fWxT3n/Tefw35rO which I can see in the header. Any idea what might be causing this strange behaviour?

Apache/2.4.54 (Ubuntu 22.04)
CSP deployed in main apache.conf file

**Comment by wyattoday** [comment]
Likely the module isn’t loaded for the subdomain. Hard to say.

**Comment by DeepFusion** [comment]
I tried a2dismod and then a2enmod and still is the same. Running out of options.
