### ISSUE TITLE
LoadModule fails with undefined symbol: my_getentropy

### ISSUE THREAD

**Issue by aliwink** [wyattoday/mod_cspnonce#16]
On debian 12 with apache 2.4.59 (custom built) and gcc 12.2 loading the compiled cspnonce module fails:

```
Cannot load modules/mod_cspnonce.so into server: /usr/local/apache/modules/mod_cspnonce.so: undefined symbol: my_getentropy
```

The module compilation shows no errors:
```
# /usr/local/apache/bin/apxs -ci mod_cspnonce.c
/usr/share/apr-1.0/build/libtool --silent --mode=compile x86_64-linux-gnu-gcc -prefer-pic  -DLINUX -D_REENTRANT -D_GNU_SOURCE  -I/usr/local/apache/include  -I/usr/include/apr-1.0   -I/usr/include/apr-1.0 -I/usr/include  -c -o mod_cspnonce.lo mod_cspnonce.c && touch mod_cspnonce.slo
/usr/share/apr-1.0/build/libtool --silent --mode=link x86_64-linux-gnu-gcc    -o mod_cspnonce.la  -rpath /usr/local/apache/modules -module -avoid-version    mod_cspnonce.lo
/usr/local/apache/build/instdso.sh SH_LIBTOOL='/usr/share/apr-1.0/build/libtool' mod_cspnonce.la /usr/local/apache/modules
/usr/share/apr-1.0/build/libtool --mode=install install mod_cspnonce.la /usr/local/apache/modules/
libtool: install: install .libs/mod_cspnonce.so /usr/local/apache/modules/mod_cspnonce.so
libtool: install: install .libs/mod_cspnonce.lai /usr/local/apache/modules/mod_cspnonce.la
libtool: install: install .libs/mod_cspnonce.a /usr/local/apache/modules/mod_cspnonce.a
libtool: install: chmod 644 /usr/local/apache/modules/mod_cspnonce.a
libtool: install: x86_64-linux-gnu-ranlib /usr/local/apache/modules/mod_cspnonce.a
libtool: finish: PATH="/root/tools:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/sbin" ldconfig -n /usr/local/apache/modules
```

Looking at the source it seems the problem is caused by declaring `my_getentropy` as an inline function:
https://github.com/wyday/mod_cspnonce/blob/f5c6bf06b7df1bb4da224dfc8b7224373b090827/mod_cspnonce.c#L57-L60

It seems there is no inlining happening during compilation and according to `readelf` the symbol `my_getentropy` exists in the symbol table but without any type (NOTYPE) or address.

Changing the declaration to 
```c
static inline int my_getentropy(void * buf, size_t buflen) 
```
seems to lead to proper inlining (`readelf` doesn't show any `my_getentropy` entries) and fixes the `LoadModule` error mentioned above.

OS: Debian GNU/Linux 12 (bookworm)
Kernel: linux-image-6.1.0-21-amd64
HTTPD: Apache/2.4.59 (Unix)
GCC: gcc version 12.2.0 (Debian 12.2.0-14)

**Comment by wyattoday** [comment]
Huh, odd. Seems like a fairly straight-forward compiler bug. Might be better off to just use a `define` to workaround the bug and get the compiled code we want.

I don't know if this is also in gcc 13.x and 14.x, and don't really have the time / patience to report it if it does (I'll let you take the lead if you want to).

**Comment by wyattoday** [comment]
Can't reproduce this on modern compilers. Presumably it's a compiler bug for older compilers.

Solution: update your compilers.

**Comment by InterLinked1** [comment]
Same as the OP, I'm also seeing this on Debian 12:

```
Cannot load /usr/lib/apache2/modules/mod_cspnonce.so into server: /usr/lib/apache2/modules/mod_cspnonce.so: undefined symbol: my_getentropy
```

```
gcc --version
gcc (Debian 12.2.0-14) 12.2.0
```

I don't think this should have been closed. There's no reason for the `my_getentropy` function to *not* be static. This is not a compiler bug, this is a bug in this project.

Indeed, works after:
```
sed -i 's/^inline int my_getentropy/static inline int my_getentropy/' mod_cspnonce.c
sed -i 's/^int my_getentropy/static int my_getentropy/' mod_cspnonce.c
```
