### ISSUE TITLE
Is there any Windows Library for Win 64 VS15?

### ISSUE THREAD

**Issue by ravhirizaldi** [wyattoday/mod_cspnonce#3]
Hello,
I'm using laragon with PHP 7.4 and Apache 2.4.35 (VS15) but your latest library for Windows is VS16, is there any version that can match with my apache? Thank you!

**Comment by wyattoday** [comment]
You can recompile it for your VS version. Or use the VS16 version of Apache. https://www.apachelounge.com/download/
