### ISSUE TITLE
Binary can't be used in Apache 2.2.29 on Windows

### ISSUE THREAD

**Issue by garykliu** [wyattoday/mod_cspnonce#5]
I have an old system running Apache 2.2.29 (Win64) on Windows Server 2012. The pre-compiled module will cause error while starting Apache. The message reads:
`httpd: Syntax error on line 508 of D:/Apache/conf/httpd.conf: API module structure 'cspnonce_module' in file D:/Apache/modules/mod_cspnonce.so is garbled - expected signature 41503232 but saw 41503234 - perhaps this is not an Apache module DSO, or was compiled for a different Apache version?`

What should I do? If I have to compile it by myself, is there any options I need to change?

Regards,
Gary

**Comment by wyattoday** [comment]
https://github.com/wyday/mod_cspnonce/pull/4#issuecomment-905826015
