### ISSUE TITLE
Compilation error with apxs [Linux RHEL]

### ISSUE THREAD

**Issue by Charliedean** [wyattoday/mod_cspnonce#7]
Hi,

Using apache 2.4 and have apxs installed.
upon compilation, we are seeing errors with TIME_UTC. Looking online it seems there have been some issues with this and MACOS, but we are using RedHat, so i would assume we wouldn't have issues with time.h

please see error from commandline.

![image](https://user-images.githubusercontent.com/68998446/145032549-c529460b-0074-44b5-987e-93f969e6a3a0.png)
Could you please assist
Thank You

**Comment by wyattoday** [comment]
Use latest XCode on macOS. Use [latest devtoolset ](https://access.redhat.com/documentation/en-us/red_hat_developer_toolset/10/html-single/10.0_release_notes/index) on Redhat/CentOS.

And google for compiler errors so you can figure out how to fix your environment so you can compile things correctly.

**Comment by Charliedean** [comment]
Hi,

I could only install devtoolset-8 due to OS and am still facing the same error. I have googled compilation errors but they are all related to MacOS.

**Comment by wyattoday** [comment]
Update to Rhel / CentOS 7 or newer. We don’t support OS that the company themselves don’t support.
